name: Generate Documentation

on:
  push:
    branches:
      - master
      - chore/autodoc-workflow
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pdoc black loguru ks_digital_twin

      - name: Generate documentation
        run: |
          export PATH=$pythonLocation/bin:$PATH
          pdoc --output-dir ./docs kos_sdk

      - name: Checkout api-docs repository
        uses: actions/checkout@v4
        with:
          repository: kscalelabs/api-docs
          path: api-docs
          token: ${{ secrets.API_DOCS_TOKEN }}
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-depth: 1
          fetch-tags: false
          show-progress: true
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Copy documentation to api-docs
        run: |
          mkdir -p api-docs/kos-sdk
          cp -r docs/kos_sdk/* api-docs/kos-sdk/

      - name: Create PR for api-docs
        run: |
          cd api-docs
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git checkout -b update-docs-${{ github.sha }}
          git add .
          git commit -m "Update demos documentation from ${{ github.sha }}" || echo "No changes to commit"
          
          # Set Git credentials explicitly instead of in the URL
          git config --global credential.helper store
          echo "https://oauth2:${{ secrets.API_DOCS_TOKEN }}@github.com" > ~/.git-credentials
          git remote set-url origin "https://oauth2:${{ secrets.API_DOCS_TOKEN }}@github.com/kscalelabs/api-docs.git"
          git push -u origin update-docs-${{ github.sha }}
          
          # Create PR using the GitHub CLI with the same token
          gh pr create --title "Update documentation" --body "Auto-generated documentation update from commit ${{ github.sha }}"
        env:
          GH_TOKEN: ${{ secrets.API_DOCS_TOKEN }}
